; No ROM code/data is stored here, this is simply a list of RAM value definitions

define entity_type                          $0300
define x_position_frac                      $0318
define x_position_low                       $0330
define x_position_high                      $0348
define y_position_frac                      $0360
define y_position_low                       $0378
define y_position_high                      $0390
define x_speed_frac                         $03A8
define x_speed                              $03C0
define y_speed_frac                         $03D8
define y_speed                              $03F0
define sprite_flags                         $0408
define entity_direction                     $0420
define entity_life                          $0450
define entity_var_a                         $0468
define entity_var_b                         $0480
define entity_var_c                         $0498
define entity_var_d                         $04B0
define entity_var_e                         $04C8
define entity_var_f                         $04E0
define entity_var_g                         $04F8
define entity_var_h                         $0510
define entity_display_flags                 $0528
define animation_frame                      $0540
define animation_index                      $0558
define animation_timer                      $0570
define entity_handler_low                   $0588
define entity_handler_high                  $05A0
define entity_flash_counter                 $05B8